use serde::{Deserialize, Serialize};
use thiserror::Error;

/// Describes a tool the model may call, following the OpenAI function-calling schema.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ToolDefinition {
    /// Always "function" in the current OpenAI spec.
    #[serde(rename = "type")]
    pub kind: String,
    pub function: FunctionDefinition,
}

impl ToolDefinition {
    pub fn function(name: impl Into<String>, description: impl Into<String>, parameters: serde_json::Value) -> Self {
        Self {
            kind: "function".to_owned(),
            function: FunctionDefinition {
                name: name.into(),
                description: description.into(),
                parameters,
            },
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct FunctionDefinition {
    pub name: String,
    pub description: String,
    /// JSON Schema object describing the function's parameters.
    pub parameters: serde_json::Value,
}

/// A single tool call emitted by the model, normalized from any backend format.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ToolCall {
    /// Opaque ID generated by the model (e.g. "call_abc123").
    /// Used to correlate a ToolResult back to this call.
    pub id: String,
    /// Always "function" for now.
    #[serde(rename = "type")]
    pub kind: String,
    pub function: FunctionCall,
}

impl ToolCall {
    pub fn new(id: impl Into<String>, name: impl Into<String>, arguments: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            kind: "function".to_owned(),
            function: FunctionCall { name: name.into(), arguments: arguments.into() },
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct FunctionCall {
    pub name: String,
    /// JSON-encoded arguments string (matches OpenAI wire format).
    pub arguments: String,
}

impl FunctionCall {
    /// Parse `arguments` as JSON. Returns an error if the string is not valid JSON.
    pub fn parse_arguments(&self) -> Result<serde_json::Value, serde_json::Error> {
        serde_json::from_str(&self.arguments)
    }
}

/// The result of executing a tool call, to be injected back into the conversation
/// as a `Role::Tool` message.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ToolResult {
    /// Must match the `ToolCall.id` this result responds to.
    pub tool_call_id: String,
    pub content: ToolResultContent,
}

impl ToolResult {
    pub fn ok(tool_call_id: impl Into<String>, output: impl Into<String>) -> Self {
        Self {
            tool_call_id: tool_call_id.into(),
            content: ToolResultContent::Text(output.into()),
        }
    }

    pub fn err(tool_call_id: impl Into<String>, error: ToolError) -> Self {
        Self {
            tool_call_id: tool_call_id.into(),
            content: ToolResultContent::Error(error.to_string()),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(untagged)]
pub enum ToolResultContent {
    Text(String),
    Error(String),
}

impl ToolResultContent {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Text(s) | Self::Error(s) => s.as_str(),
        }
    }
}

/// Errors a tool implementation can return.
#[derive(Debug, Error, Clone, PartialEq)]
pub enum ToolError {
    #[error("unauthorized: {0}")]
    Unauthorized(String),
    #[error("not found: {0}")]
    NotFound(String),
    #[error("invalid arguments: {0}")]
    InvalidArguments(String),
    #[error("execution failed: {0}")]
    ExecutionFailed(String),
    #[error("timeout")]
    Timeout,
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    // --- ToolDefinition ---

    #[test]
    fn tool_definition_serde_round_trip() {
        let def = ToolDefinition::function(
            "read_file",
            "Read a file from the workspace",
            json!({ "type": "object", "properties": { "path": { "type": "string" } }, "required": ["path"] }),
        );
        let json = serde_json::to_string(&def).unwrap();
        let back: ToolDefinition = serde_json::from_str(&json).unwrap();
        assert_eq!(def, back);
    }

    #[test]
    fn tool_definition_type_field_is_function() {
        let def = ToolDefinition::function("f", "d", json!({}));
        let json = serde_json::to_string(&def).unwrap();
        let v: serde_json::Value = serde_json::from_str(&json).unwrap();
        assert_eq!(v["type"], "function");
    }

    // --- ToolCall ---

    #[test]
    fn tool_call_serde_round_trip() {
        let call = ToolCall::new("call_001", "read_file", r#"{"path":"src/main.rs"}"#);
        let json = serde_json::to_string(&call).unwrap();
        let back: ToolCall = serde_json::from_str(&json).unwrap();
        assert_eq!(call, back);
    }

    #[test]
    fn tool_call_type_field_is_function() {
        let call = ToolCall::new("id1", "fn", "{}");
        let v: serde_json::Value = serde_json::to_value(&call).unwrap();
        assert_eq!(v["type"], "function");
    }

    #[test]
    fn function_call_parse_arguments_valid_json() {
        let call = ToolCall::new("id1", "read_file", r#"{"path":"src/lib.rs"}"#);
        let args = call.function.parse_arguments().unwrap();
        assert_eq!(args["path"], "src/lib.rs");
    }

    #[test]
    fn function_call_parse_arguments_invalid_json() {
        let call = ToolCall::new("id1", "fn", "not json");
        assert!(call.function.parse_arguments().is_err());
    }

    // --- ToolResult ---

    #[test]
    fn tool_result_ok_serde_round_trip() {
        let result = ToolResult::ok("call_001", "file contents here");
        let json = serde_json::to_string(&result).unwrap();
        let back: ToolResult = serde_json::from_str(&json).unwrap();
        assert_eq!(result, back);
    }

    #[test]
    fn tool_result_err_contains_error_message() {
        let result = ToolResult::err("call_002", ToolError::Unauthorized("../etc/passwd".into()));
        assert_eq!(result.content.as_str(), "unauthorized: ../etc/passwd");
    }

    #[test]
    fn tool_result_content_as_str() {
        let ok = ToolResultContent::Text("hello".into());
        let err = ToolResultContent::Error("oops".into());
        assert_eq!(ok.as_str(), "hello");
        assert_eq!(err.as_str(), "oops");
    }

    // --- ToolError ---

    #[test]
    fn tool_error_display_unauthorized() {
        let e = ToolError::Unauthorized("path traversal".into());
        assert_eq!(e.to_string(), "unauthorized: path traversal");
    }

    #[test]
    fn tool_error_display_timeout() {
        assert_eq!(ToolError::Timeout.to_string(), "timeout");
    }

    #[test]
    fn tool_error_display_invalid_arguments() {
        let e = ToolError::InvalidArguments("missing 'path'".into());
        assert_eq!(e.to_string(), "invalid arguments: missing 'path'");
    }

    #[test]
    fn tool_error_display_execution_failed() {
        let e = ToolError::ExecutionFailed("rg not found".into());
        assert_eq!(e.to_string(), "execution failed: rg not found");
    }

    #[test]
    fn tool_error_display_not_found() {
        let e = ToolError::NotFound("src/missing.rs".into());
        assert_eq!(e.to_string(), "not found: src/missing.rs");
    }

    // --- JSON Schema structure for ToolDefinition.parameters ---

    #[test]
    fn tool_definition_parameters_preserved_as_json() {
        let params = json!({
            "type": "object",
            "properties": {
                "path": { "type": "string", "description": "File path" },
                "encoding": { "type": "string", "enum": ["utf-8", "ascii"] }
            },
            "required": ["path"]
        });
        let def = ToolDefinition::function("read_file", "Read a file", params.clone());
        let v: serde_json::Value = serde_json::to_value(&def).unwrap();
        assert_eq!(v["function"]["parameters"], params);
    }
}
